"""add user_id to activities

Revision ID: a103f4f91bde
Revises: 5359a0572460
Create Date: 2026-02-21 20:17:44.826229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a103f4f91bde'
down_revision: Union[str, Sequence[str], None] = '5359a0572460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'user_id')
    # ### end Alembic commands ###
